[2025-08-10T15:30:47.603+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-10T15:30:47.734+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_data_pipeline.run_dbt_transformations scheduled__2025-08-09T00:00:00+00:00 [queued]>
[2025-08-10T15:30:47.739+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_data_pipeline.run_dbt_transformations scheduled__2025-08-09T00:00:00+00:00 [queued]>
[2025-08-10T15:30:47.740+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-08-10T15:30:47.747+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): run_dbt_transformations> on 2025-08-09 00:00:00+00:00
[2025-08-10T15:30:47.754+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'weather_data_pipeline', 'run_dbt_transformations', 'scheduled__2025-08-09T00:00:00+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/weather_dags.py', '--cfg-path', '/tmp/tmp7om80qi0']
[2025-08-10T15:30:47.757+0000] {standard_task_runner.py:91} INFO - Job 9: Subtask run_dbt_transformations
[2025-08-10T15:30:47.757+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=864) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-08-10T15:30:47.757+0000] {standard_task_runner.py:63} INFO - Started process 866 to run task
[2025-08-10T15:30:47.802+0000] {task_command.py:426} INFO - Running <TaskInstance: weather_data_pipeline.run_dbt_transformations scheduled__2025-08-09T00:00:00+00:00 [running]> on host a958f78a1f45
[2025-08-10T15:30:47.872+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Hendi Irwanto' AIRFLOW_CTX_DAG_ID='weather_data_pipeline' AIRFLOW_CTX_TASK_ID='run_dbt_transformations' AIRFLOW_CTX_EXECUTION_DATE='2025-08-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-08-09T00:00:00+00:00'
[2025-08-10T15:30:47.873+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-10T15:30:47.884+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-10T15:30:47.884+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/weather_dags.py", line 20, in run_dbt_transformations
    subprocess.run(["dbt", "run", "--profiles-dir", "/opt/data-engineer/weather-project/dbt/weather_dbt"], check=True)
  File "/usr/local/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.12/subprocess.py", line 1955, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'dbt'
[2025-08-10T15:30:47.895+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=weather_data_pipeline, task_id=run_dbt_transformations, run_id=scheduled__2025-08-09T00:00:00+00:00, execution_date=20250809T000000, start_date=20250810T153047, end_date=20250810T153047
[2025-08-10T15:30:47.903+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 9 for task run_dbt_transformations ([Errno 2] No such file or directory: 'dbt'; 866)
[2025-08-10T15:30:47.933+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-08-10T15:30:47.951+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-10T15:30:47.952+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-08-10T16:41:41.971+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-10T16:41:42.098+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_data_pipeline.run_dbt_transformations scheduled__2025-08-09T00:00:00+00:00 [queued]>
[2025-08-10T16:41:42.103+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_data_pipeline.run_dbt_transformations scheduled__2025-08-09T00:00:00+00:00 [queued]>
[2025-08-10T16:41:42.103+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-08-10T16:41:42.111+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): run_dbt_transformations> on 2025-08-09 00:00:00+00:00
[2025-08-10T16:41:42.118+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'weather_data_pipeline', 'run_dbt_transformations', 'scheduled__2025-08-09T00:00:00+00:00', '--job-id', '26', '--raw', '--subdir', 'DAGS_FOLDER/weather_dags.py', '--cfg-path', '/tmp/tmprxurr_mo']
[2025-08-10T16:41:42.120+0000] {standard_task_runner.py:91} INFO - Job 26: Subtask run_dbt_transformations
[2025-08-10T16:41:42.120+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=316) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-08-10T16:41:42.120+0000] {standard_task_runner.py:63} INFO - Started process 318 to run task
[2025-08-10T16:41:42.164+0000] {task_command.py:426} INFO - Running <TaskInstance: weather_data_pipeline.run_dbt_transformations scheduled__2025-08-09T00:00:00+00:00 [running]> on host 49775de909c4
[2025-08-10T16:41:42.236+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Hendi Irwanto' AIRFLOW_CTX_DAG_ID='weather_data_pipeline' AIRFLOW_CTX_TASK_ID='run_dbt_transformations' AIRFLOW_CTX_EXECUTION_DATE='2025-08-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-08-09T00:00:00+00:00'
[2025-08-10T16:41:42.237+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-10T16:41:42.246+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-08-10T16:41:42.246+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'dbt run --project-dir /opt/data-engineer/weather-project/dbt/weather_dbt']
[2025-08-10T16:41:42.255+0000] {subprocess.py:86} INFO - Output:
[2025-08-10T16:41:43.553+0000] {subprocess.py:93} INFO - Usage: dbt run [OPTIONS]
[2025-08-10T16:41:43.553+0000] {subprocess.py:93} INFO - Try 'dbt run -h' for help.
[2025-08-10T16:41:43.553+0000] {subprocess.py:93} INFO - 
[2025-08-10T16:41:43.553+0000] {subprocess.py:93} INFO - Error: Invalid value for '--profiles-dir': Path '/root/.dbt' does not exist.
[2025-08-10T16:41:43.702+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2025-08-10T16:41:43.703+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-10T16:41:43.714+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-08-10T16:41:43.717+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=weather_data_pipeline, task_id=run_dbt_transformations, run_id=scheduled__2025-08-09T00:00:00+00:00, execution_date=20250809T000000, start_date=20250810T164142, end_date=20250810T164143
[2025-08-10T16:41:43.725+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 26 for task run_dbt_transformations (Bash command failed. The command returned a non-zero exit code 2.; 318)
[2025-08-10T16:41:43.758+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-08-10T16:41:43.775+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-10T16:41:43.776+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-08-10T16:48:29.313+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-10T16:48:29.450+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_data_pipeline.run_dbt_transformations scheduled__2025-08-09T00:00:00+00:00 [queued]>
[2025-08-10T16:48:29.456+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_data_pipeline.run_dbt_transformations scheduled__2025-08-09T00:00:00+00:00 [queued]>
[2025-08-10T16:48:29.456+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-08-10T16:48:29.463+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): run_dbt_transformations> on 2025-08-09 00:00:00+00:00
[2025-08-10T16:48:29.471+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'weather_data_pipeline', 'run_dbt_transformations', 'scheduled__2025-08-09T00:00:00+00:00', '--job-id', '34', '--raw', '--subdir', 'DAGS_FOLDER/weather_dags.py', '--cfg-path', '/tmp/tmpdq2pisea']
[2025-08-10T16:48:29.473+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=527) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-08-10T16:48:29.473+0000] {standard_task_runner.py:91} INFO - Job 34: Subtask run_dbt_transformations
[2025-08-10T16:48:29.473+0000] {standard_task_runner.py:63} INFO - Started process 531 to run task
[2025-08-10T16:48:29.520+0000] {task_command.py:426} INFO - Running <TaskInstance: weather_data_pipeline.run_dbt_transformations scheduled__2025-08-09T00:00:00+00:00 [running]> on host 49775de909c4
[2025-08-10T16:48:29.592+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Hendi Irwanto' AIRFLOW_CTX_DAG_ID='weather_data_pipeline' AIRFLOW_CTX_TASK_ID='run_dbt_transformations' AIRFLOW_CTX_EXECUTION_DATE='2025-08-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-08-09T00:00:00+00:00'
[2025-08-10T16:48:29.592+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-10T16:48:29.602+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-08-10T16:48:29.602+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'dbt run --project-dir /opt/data-engineer/weather-project/dbt/weather_dbt --profiles-dir /opt/data-engineer/weather-project/dbt/weather_dbt/.dbt']
[2025-08-10T16:48:29.611+0000] {subprocess.py:86} INFO - Output:
[2025-08-10T16:48:30.959+0000] {subprocess.py:93} INFO - [0m16:48:30  Running with dbt=1.10.7
[2025-08-10T16:48:31.216+0000] {subprocess.py:93} INFO - [0m16:48:31  Registered adapter: postgres=1.9.0
[2025-08-10T16:48:31.426+0000] {subprocess.py:93} INFO - [0m16:48:31  [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
[2025-08-10T16:48:31.426+0000] {subprocess.py:93} INFO - There are 1 unused configuration paths:
[2025-08-10T16:48:31.426+0000] {subprocess.py:93} INFO - - models.dbt_date
[2025-08-10T16:48:31.552+0000] {subprocess.py:93} INFO - [0m16:48:31  Found 5 models, 2 sources, 576 macros
[2025-08-10T16:48:31.554+0000] {subprocess.py:93} INFO - [0m16:48:31
[2025-08-10T16:48:31.554+0000] {subprocess.py:93} INFO - [0m16:48:31  Concurrency: 1 threads (target='dev')
[2025-08-10T16:48:31.555+0000] {subprocess.py:93} INFO - [0m16:48:31
[2025-08-10T16:48:31.697+0000] {subprocess.py:93} INFO - [0m16:48:31  1 of 5 START sql table model dimension.dim_dates ............................... [RUN]
[2025-08-10T16:48:31.955+0000] {subprocess.py:93} INFO - [0m16:48:31  1 of 5 OK created sql table model dimension.dim_dates .......................... [[32mSELECT 1829[0m in 0.26s]
[2025-08-10T16:48:31.957+0000] {subprocess.py:93} INFO - [0m16:48:31  2 of 5 START sql table model dimension.dim_locations ........................... [RUN]
[2025-08-10T16:48:31.993+0000] {subprocess.py:93} INFO - [0m16:48:31  2 of 5 OK created sql table model dimension.dim_locations ...................... [[32mSELECT 100[0m in 0.03s]
[2025-08-10T16:48:31.995+0000] {subprocess.py:93} INFO - [0m16:48:31  3 of 5 START sql view model staging.stg_weather_data ........................... [RUN]
[2025-08-10T16:48:32.095+0000] {subprocess.py:93} INFO - [0m16:48:32  3 of 5 OK created sql view model staging.stg_weather_data ...................... [[32mCREATE VIEW[0m in 0.10s]
[2025-08-10T16:48:32.098+0000] {subprocess.py:93} INFO - [0m16:48:32  4 of 5 START sql table model marts.mart_avg_temp_by_day_of_week ................ [RUN]
[2025-08-10T16:48:32.135+0000] {subprocess.py:93} INFO - [0m16:48:32  4 of 5 OK created sql table model marts.mart_avg_temp_by_day_of_week ........... [[32mSELECT 700[0m in 0.04s]
[2025-08-10T16:48:32.137+0000] {subprocess.py:93} INFO - [0m16:48:32  5 of 5 START sql table model marts.mart_daily_weather .......................... [RUN]
[2025-08-10T16:48:32.174+0000] {subprocess.py:93} INFO - [0m16:48:32  5 of 5 OK created sql table model marts.mart_daily_weather ..................... [[32mSELECT 900[0m in 0.04s]
[2025-08-10T16:48:32.187+0000] {subprocess.py:93} INFO - [0m16:48:32
[2025-08-10T16:48:32.187+0000] {subprocess.py:93} INFO - [0m16:48:32  Finished running 4 table models, 1 view model in 0 hours 0 minutes and 0.63 seconds (0.63s).
[2025-08-10T16:48:32.222+0000] {subprocess.py:93} INFO - [0m16:48:32
[2025-08-10T16:48:32.222+0000] {subprocess.py:93} INFO - [0m16:48:32  [32mCompleted successfully[0m
[2025-08-10T16:48:32.223+0000] {subprocess.py:93} INFO - [0m16:48:32
[2025-08-10T16:48:32.223+0000] {subprocess.py:93} INFO - [0m16:48:32  Done. PASS=5 WARN=0 ERROR=0 SKIP=0 NO-OP=0 TOTAL=5
[2025-08-10T16:48:33.743+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-08-10T16:48:33.743+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-10T16:48:33.767+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=weather_data_pipeline, task_id=run_dbt_transformations, run_id=scheduled__2025-08-09T00:00:00+00:00, execution_date=20250809T000000, start_date=20250810T164829, end_date=20250810T164833
[2025-08-10T16:48:33.794+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-08-10T16:48:33.809+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-10T16:48:33.810+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
