[2025-08-18T01:29:54.030+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-18T01:29:54.155+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_data_pipeline.fetch_geolocation_data manual__2025-08-18T01:29:52.036937+00:00 [queued]>
[2025-08-18T01:29:54.160+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_data_pipeline.fetch_geolocation_data manual__2025-08-18T01:29:52.036937+00:00 [queued]>
[2025-08-18T01:29:54.160+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-08-18T01:29:54.168+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): fetch_geolocation_data> on 2025-08-18 01:29:52.036937+00:00
[2025-08-18T01:29:54.175+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'weather_data_pipeline', 'fetch_geolocation_data', 'manual__2025-08-18T01:29:52.036937+00:00', '--job-id', '60', '--raw', '--subdir', 'DAGS_FOLDER/weather_dags.py', '--cfg-path', '/tmp/tmpn6zlgyit']
[2025-08-18T01:29:54.177+0000] {standard_task_runner.py:91} INFO - Job 60: Subtask fetch_geolocation_data
[2025-08-18T01:29:54.177+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=524) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-08-18T01:29:54.177+0000] {standard_task_runner.py:63} INFO - Started process 526 to run task
[2025-08-18T01:29:54.219+0000] {task_command.py:426} INFO - Running <TaskInstance: weather_data_pipeline.fetch_geolocation_data manual__2025-08-18T01:29:52.036937+00:00 [running]> on host 23863237c1a1
[2025-08-18T01:29:54.294+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Hendi Irwanto' AIRFLOW_CTX_DAG_ID='weather_data_pipeline' AIRFLOW_CTX_TASK_ID='fetch_geolocation_data' AIRFLOW_CTX_EXECUTION_DATE='2025-08-18T01:29:52.036937+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-18T01:29:52.036937+00:00'
[2025-08-18T01:29:54.294+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-18T01:29:55.300+0000] {logging_mixin.py:188} INFO - Geolocation data fetched successfully.
[2025-08-18T01:29:55.306+0000] {logging_mixin.py:188} INFO - Geolocation data processed into DataFrame. Shape: (100, 5)
[2025-08-18T01:32:07.940+0000] {logging_mixin.py:188} INFO - An error occurred while loading data into the database: (psycopg2.OperationalError) connection to server at "172.18.0.2", port 5432 failed: Connection timed out
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2025-08-18T01:32:07.941+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-08-18T01:32:07.941+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-18T01:32:07.953+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=weather_data_pipeline, task_id=fetch_geolocation_data, run_id=manual__2025-08-18T01:29:52.036937+00:00, execution_date=20250818T012952, start_date=20250818T012954, end_date=20250818T013207
[2025-08-18T01:32:07.978+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-08-18T01:32:07.999+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-08-18T01:32:08.000+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
